package org.pancho.model.enums;

import org.pancho.model.ISystemMessage;

public enum ErrorMessage implements ISystemMessage {

    INVALID_NUMBER_OF_PARAMETERS("ERROR: INVALID NUMBER OF PARAMETERS"),
    INVALID_TYPE_OF_DATA("ERROR: WRONG TYPE OF DATA"),
    INVALID_EMAIL("ERROR: INVALID EMAIL"),
    INVALID_LANGUAGE("ERROR: INVALID LANGUAGE"),
    INVALID_PHOTO("ERROR: INVALID PHOTO"),
    USER_ALREADY_EXISTS("ERROR: USER ALREADY EXISTS"),
    WRONG_EMAIL_OR_PASSWORD("ERROR: INVALID EMAIL OR PASSWORD"),
    NO_UPM_EMAIL("ERROR: EMAIL NOT REGISTERED IN THE UPM"),
    INVALID_LOGIN("ERROR: INVALID LOGIN"),
    ALREADY_LOGGED_IN("ERROR: ALREADY LOGGED IN"),
    USER_NOT_OWNER("ERROR: USER IS NOT AN OWNER"),
    INVALID_RIAC_CODE("ERROR: INVALID RIAC CODE"),
    INVALID_POLICY_NUMBER("ERROR: INVALID POLICY NUMBER"),
    INVALID_PET("ERROR: INVALID PET"),
    INVALID_PANCHO_POINTS("ERROR: INVALID PANCHO POINTS"),
    INVALID_COST("ERROR: INVALID COST"),
    INVALID_DATE("ERROR: INVALID DATE"),
    PET_ALREADY_HAS_CARE("ERROR: PET ALREADY HAS CARE"),
    PET_ALREADY_EXISTS("ERROR: PET ALREADY EXISTS"),
    COMMAND_NOT_FOUND("ERROR: COMMAND NOT FOUND"),
    USER_NOT_OWNER_OF_PET("ERROR: USER IS NOT THE OWNER OF THE PET");

    private final String message;

    ErrorMessage(String message) {
        this.message = message;
    }

    @Override
    public String getMessage() {
        return this.message;
    }

}